#!/bin/sh
echo 13 > /sys/class/gpio/export
echo 20 > /sys/class/gpio/export
sleep 0.1
echo out > /sys/class/gpio/gpio13/direction
echo in > /sys/class/gpio/gpio20/direction
echo 1 > /sys/class/gpio/gpio13/value
export RESULT=$(cat /sys/class/gpio/gpio20/value)
echo 13 > /sys/class/gpio/unexport
echo 20 > /sys/class/gpio/unexport
echo "Content-Type: text/html"
echo ""
echo "<html><head><title>Rocket Launcher - Test $RESULT</title></head><body><p>"
if test $RESULT = 1
then
    echo "Test failed! Check continuity."
else
    echo "Test success! Ready to launch."
fi
echo "</p><p><a href="/">Back</a></p></body></html>"
